// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassAjax.Models;

public partial class Address
{
    public int Id { get; set; }

    public string City { get; set; }

    public string SiteId { get; set; }

    public string Road { get; set; }
}